trigger:
      branches:
        include: 
        - '*'

resources:
  repositories:
  - repository: templates
    type: git
    name: templates
    ref: refs/heads/main

variables:
  - template: template-vars.yml@templates

stages:
 - template: ${{ variables.l1_pipeline_template }}@templates